  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  uwsgi:
    restart: always
  
    # IMPORTANT: update the tag to coincide with release version
    image: quay.io/vanessa/sregistry
    env_file:
      - ./.minio-env
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
      # uncomment for PAM auth
      - /etc/passwd:/etc/passwd 
      - ./PAM/shadow:/etc/shadow
    links:
      - minio
      - redis
      - db
  
  nginx:
    restart: always
    image: quay.io/vanessa/sregistry_nginx
    ports:
      - "7319:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
      - ./ssl/certs/${DOM_CERT}:/etc/ssl/certs/chained.pem:ro
      - ./ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - ./ssl/private/${DOM_KEY}:/etc/ssl/private/domain.key:ro
      # volumes_from: uwsgi
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    links:
      - uwsgi
      - db
  
  redis:
    restart: always
    image: redis:latest
  
  scheduler:
  
    # IMPORTANT: update the tag to coincide with release version
    image: quay.io/vanessa/sregistry
    command: python /code/manage.py rqscheduler
    volumes:
      - .:/code
      # volumes_from: uwsgi
      - ./static:/var/www/static
      - ./images:/var/www/images
    env_file:
      - ./.minio-env
    links:
      - minio
      - redis
      - db
  
  worker:
  
    # IMPORTANT: update the tag to coincide with release version
    image: quay.io/vanessa/sregistry
    command: python /code/manage.py rqworker default
    volumes:
      - .:/code
      # volumes_from: uwsgi
      - ./static:/var/www/static
      - ./images:/var/www/images
    env_file:
      - ./.minio-env
    links:
      - minio
      - redis
      - db
  
  minio:
    image: minio/minio
    volumes:
      - ./minio-images/drive1:/images1
      - ./minio-images/drive2:/images2
      - ./minio-images/drive3:/images3
      - ./minio-images/drive4:/images4
      - ./ssl/certs/${DOM_CERT}:/root/.minio/certs/public.crt:ro
      - ./ssl/private/${DOM_KEY}:/root/.minio/certs/private.key:ro
    env_file:
     - ./.minio-env
    ports:
     - "9000:9000"  
    command: ["server", "images{1...4}"]
